### ISSUE TITLE
Error in .ply

### ISSUE THREAD

**Issue by gangweix** [jzhangbs/DTUeval-python#3]
TriangleMesh with 51069949 points and 0 triangles.
sample pcd from mesh:  11%|█████                                         | 1/9 [00:07<01:02,  7.76s/it]Traceback (most recent call last):
  File "pc_eval.py", line 70, in <module>
    new_pts = np.concatenate(new_pts, axis=0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

Hi, I use IterMVS (CVPR 2022) to generate .ply, however  during the evaluation, I encountered an error that there is no triangles, how can I solve it？

**Comment by jzhangbs** [comment]
Hi @gangweiX, I guess you are evaluating point clouds. If so, you need to specify that in the arguments by `--mode pcd`.

**Comment by gangweix** [comment]
Ok, thanks.
